using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace MoreAsyncLINQ.Generators;

internal static class Writers
{
    public static readonly string[] Ordinals = ["first", "second", "third", "fourth", "fifth", "sixth", "seventh", "eighth"];

    public static IndentedTextWriter CreateSourceWriter(StringWriter stringWriter, params string[] additionalUsings)
    {
        var writer = new IndentedTextWriter(stringWriter);

        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine();

        var usings =
            new List<string>(additionalUsings)
            {
                "System",
                "System.Collections.Generic",
                "System.Linq",
                "System.Threading",
                "System.Threading.Tasks",
            };

        foreach (var @using in usings.OrderBy(_ => _))
        {
            writer.WriteLine($"using {@using};");
        }
        
        writer.WriteLine();
        writer.WriteLine("namespace MoreAsyncLINQ;");
        writer.WriteLine();
        writer.WriteLine("static partial class MoreAsyncEnumerable");

        return writer;
    }

    public static IndentedTextWriter CreateXmlDocWriter(IndentedTextWriter writer)
    {
        var xmlDocWriter = new IndentedTextWriter(writer, "/// ");
        xmlDocWriter.Indent++;
        return xmlDocWriter;
    }

    public static string GetFuncType(string[] inputTypes, string outputType, bool isAsync) =>
        isAsync
            ? $"Func<{string.Join(", ", inputTypes)}, CancellationToken, ValueTask<{outputType}>>"
            : $"Func<{string.Join(", ", inputTypes)}, {outputType}>";

    public static string[] GetTypeParams(int arity, string prefix = "T") =>
        Enumerable.Range(1, arity).
            Select(index => $"{prefix}{index}").
            ToArray();

    public static void WriteNullCheck(IndentedTextWriter writer, string paramName) =>
        writer.WriteLine($"if ({paramName} is null) throw new ArgumentNullException(nameof({paramName}));");
}

